version: '{build}-{branch}'
os: Default Azure
platform: x64
clone_depth: 1
environment:
  global:
    CYGWIN_ROOT: C:\cygwin
    SNAPSHOT: snapshot
    SSH_CONFIG: ssh_config
  matrix:
    - BOX: pashkin/ubuntu-trusty32-salt-beryllium
      SALT_VERSION: 2015.8
init:
  - cmd: set PATH=C:\Python27;C:\Python27\Scripts;%PATH%
  - cmd: |
      mkdir C:\downloads > NUL
      cd C:\downloads
  # Install Pip and Tox
  - cmd: |
      curl -sSLO https://bootstrap.pypa.io/get-pip.py
      python get-pip.py
      pip install tox==2.3.1
  # Install Vagrant and VirtualBox
  - cmd: |
      curl -sSLO https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1.msi
      curl -sSLO http://download.virtualbox.org/virtualbox/5.0.14/VirtualBox-5.0.14-105127-Win.exe
      msiexec.exe /a vagrant_1.8.1.msi /qb TARGETDIR=C:\Vagrant
      VirtualBox-5.0.14-105127-Win.exe -silent -logging -msiparams INSTALLDIR=C:\VBox
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
before_build:
  - cmd: cmd /C "set "PATH=%CYGWIN_ROOT%\bin;%PATH%" && make snapshot && make ssh_config"
build_script:
  - cmd: tox -v
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
